notify-updates: true
# Multi game support means, that you can run multiple things in your server including the practice.
# The plugin only uses the lobby (which you can set) and the arenas worlds.
multi-game-support: false
# You can set the arenas world name which contains all the arenas.
arena-world-name: arenas
# Knockback modifier - it depends on the hit delay very much. You should test what is the optimal for you.
knockback:
  combo:
    air-horizontal: 2.8
    air-vertical: 2.8
    horizontal: 2.5
    vertical: 2.5
# How long player can accept request to duel in seconds
request-time: 120

#
# Ranked settings
ranked:
  elo-range-time: 5 # Sec
  elo-range-increase: 20 # Range
  max-range: 300
  elo-change: 10
  min-unranked-wins: 10 # Players have to win at least this many unrankeds before they can play ranked games.
  default-elo: 1000
  ranked-per-day: # You can continue the list below. Don't remove the "default" section. It reset at midnight every day or when you restart the server.
    default: 1
    R20:
      permission: "zonepractice.ranked.20"
      allowed-rankeds: 20
    R30:
      permission: "zonepractice.ranked.30"
      allowed-rankeds: 30
    R50:
      permission: "zonepractice.ranked.50"
      allowed-rankeds: 50
#
# Match settings
match-settings:
  build-limit: 4 # Counts from the first players positions y level.
  start-countdown: 5 # Countdown when the match starts.
  after-countdown: 3 # After the match is over this countdown start, and when it's over the players teleport back to lobby.
  remove-empty-bottle: true # Removes empty potion bottles after the player use it.
  hide-other-spectators: true # Hide the spectators from each other.
  enderpearl:
    cooldown: 13 # Sec
  party:
    split-team-damage: false # In party split games, players with the same team can't hurt each other (if false).
#
# Party settings
party-settings:
  max-party-members:
    default: 6 # Maximum party members, if the owner don't have permission to change it.
  party-invite-cooldown: 60 # After these seconds, the party invite will expire.
#
# Leaderboard settings
show-player: 5 # The leaderboard will show the first this many player.
#
# World settings
world-settings:
  cancel-weather: true
  remove-arrows: true
# Sidebar
sidebar: true # Enable the sidebar
admin-sidebar: true # Show TPS or not